version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package -Dmaven.test.skip=true
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/mama.earth-0.0.1-SNAPSHOT.jar
  discard-paths: yes
